- generic [ref=e166]:
  - navigation [ref=e167]:
    - generic [ref=e168]: 💬 Chat
    - generic [ref=e169]:
      - link "Public Rooms" [ref=e170] [cursor=pointer]:
        - /url: /catalog
      - link "Private Rooms" [ref=e171] [cursor=pointer]:
        - /url: /my-rooms
      - link "Contacts" [ref=e172] [cursor=pointer]:
        - /url: /friends
      - link "Sessions" [ref=e173] [cursor=pointer]:
        - /url: /sessions
      - generic [ref=e175] [cursor=pointer]: rkovalenko ▼
    - button "Sign out" [ref=e176] [cursor=pointer]
  - generic [ref=e177]:
    - complementary [ref=e178]:
      - generic [ref=e179]:
        - textbox "Search" [ref=e181]
        - generic [ref=e182]:
          - heading "ROOMS" [level=3] [ref=e183]
          - generic [ref=e184]:
            - generic [ref=e185] [cursor=pointer]: ▼ Public Rooms
            - generic [ref=e186]:
              - generic "Navigate Test Room" [ref=e187] [cursor=pointer]
              - generic "Test Create Room" [ref=e188] [cursor=pointer]
              - generic "Priority 3 Test Room" [ref=e189] [cursor=pointer]
              - generic "My updated room" [ref=e190] [cursor=pointer]
              - generic "General Discussion" [ref=e191] [cursor=pointer]
              - generic "Test Room" [ref=e192] [cursor=pointer]
            - generic [ref=e193] [cursor=pointer]: ▼ Private Rooms
            - generic [ref=e194]:
              - generic "Roma 2" [ref=e195] [cursor=pointer]
              - generic "Room 2" [ref=e196] [cursor=pointer]
        - generic [ref=e197]:
          - heading "CONTACTS" [level=3] [ref=e198]
          - generic "bob2bob2" [ref=e200] [cursor=pointer]
        - button "[Create room]" [ref=e201] [cursor=pointer]
      - button "◀" [ref=e202] [cursor=pointer]
    - main [ref=e203]:
      - generic [ref=e204]:
        - generic [ref=e205]:
          - heading "Navigate Test Room" [level=2] [ref=e206]
          - paragraph [ref=e207]: Should navigate on create
        - paragraph [ref=e209]: No messages yet. Start the conversation!
        - generic [ref=e211]:
          - button "😀" [ref=e213] [cursor=pointer]
          - button "📎" [ref=e214] [cursor=pointer]
          - textbox "message input" [ref=e215]
          - button "Send" [disabled] [ref=e216]
    - complementary [ref=e217]:
      - generic [ref=e219]:
        - heading "Room info" [level=2] [ref=e220]
        - generic [ref=e221]:
          - generic [ref=e222]:
            - generic [ref=e223]: "Type:"
            - generic [ref=e224]: Public
          - generic [ref=e225]:
            - generic [ref=e226]: "Owner:"
            - generic [ref=e227]: rkovalenko
        - generic [ref=e228]:
          - heading "Members (0)" [level=3] [ref=e229]
          - generic [ref=e231]: No regular members
        - generic [ref=e232]:
          - button "📨 Invite user" [ref=e233] [cursor=pointer]
          - button "⚙️ Manage room" [ref=e234] [cursor=pointer]